name: crawl

on:
  schedule:
    - cron: "0 21 * * *" # 06:00 JST daily
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python pipeline.py
      - name: Commit & Push
        run: |
          git config user.name "crawler-bot"
          git config user.email "crawler@users.noreply.github.com"
          git add datastore/references.*
          git commit -m "update: $(date -u +%FT%TZ)" || echo "no changes"
          git push
