name: Update references (daily)

on:
  schedule:
    - cron: "0 21 * * *"   # JST 06:00（UTC 21:00）に毎日実行
  workflow_dispatch:       # 手動実行ボタン

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run updater
        run: python pipeline.py

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update data: $(date -u +%FT%TZ)"
          file_pattern: datastore/references.json datastore/references.yaml
          commit_user_name: crawler-bot
          commit_user_email: crawler@users.noreply.github.com
          commit_author: crawler-bot <crawler@users.noreply.github.com>
